{% set name = "datastar-py" %}
{% set version = "0.4.4" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/datastar_py-{{ version }}.tar.gz
  sha256: 5a0720630a5f249b008f0ab0b42b1471ed19fa74540a69c020c34bb8437ad53a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - datastar_py
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Helper functions and classes for the Datastar library
  home: https://data-star.dev/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
