# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: datastar-py
  version: "0.6.5"
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/datastar_py-${{ version }}.tar.gz
  sha256: a8ec90077b455b0870586ae5f454ae3b0c2c392cf8cdf6853a03adb1c9158b54

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - brotlipy
    - django
    - fastapi
    - quart
    - sanic
    - starlette

tests:
  - python:
      imports:
        - datastar_py
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Helper functions and classes for the Datastar library
  license: MIT
  license_file: LICENSE
  homepage: https://data-star.dev/

extra:
  recipe-maintainers:
    - rxm7706
